// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQfIvGn5yP_wtYG3piUZb7cTE4dQMWFAs',
    appId: '1:323541638484:web:264b21914bdb0459bcbcc1',
    messagingSenderId: '323541638484',
    projectId: 'fees-tracking',
    authDomain: 'fees-tracking.firebaseapp.com',
    storageBucket: 'fees-tracking.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAr-yI9adYs0lyDn6jS9pIOYxfS-4Ou-c',
    appId: '1:323541638484:android:1d22b3dd9d6e3e97bcbcc1',
    messagingSenderId: '323541638484',
    projectId: 'fees-tracking',
    storageBucket: 'fees-tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApZkGWRIenB1zLkXI4oUorG7l83M_mLTg',
    appId: '1:323541638484:ios:0a680d9960b3f1b4bcbcc1',
    messagingSenderId: '323541638484',
    projectId: 'fees-tracking',
    storageBucket: 'fees-tracking.appspot.com',
    iosBundleId: 'com.example.feesTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApZkGWRIenB1zLkXI4oUorG7l83M_mLTg',
    appId: '1:323541638484:ios:0a680d9960b3f1b4bcbcc1',
    messagingSenderId: '323541638484',
    projectId: 'fees-tracking',
    storageBucket: 'fees-tracking.appspot.com',
    iosBundleId: 'com.example.feesTracking',
  );
}
